/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalhoprogdesktop;

import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Software extends javax.swing.JFrame {

    private DefaultTableModel  modelo = new DefaultTableModel();
    private int linhaSelecionada = -1;
    
    private DefaultTableModel  modelo2 = new DefaultTableModel();
    private int linhaSelecionada2 = -1;
    
    Cliente cliente = new Cliente();
    Veiculo veiculo = new Veiculo();
    Servicos servicos = new Servicos();
    
    public Software() {
        
        initComponents();
        setLocationRelativeTo(this);
        carregaTabela();
        
    }

    public void carregaTabela(){
        
       modelo.addColumn("Item");
       modelo.addColumn("Serviço");
       modelo.addColumn("Valor - Peca");
       modelo.addColumn("Quantidade");
       modelo.addColumn("Mão de Obra");
       tbInformacoesServico.setModel(modelo);
       tbInformacoesServico.getColumnModel().getColumn(0).setPreferredWidth(0);
       tbInformacoesServico.getColumnModel().getColumn(1).setPreferredWidth(0);
       tbInformacoesServico.getColumnModel().getColumn(2).setPreferredWidth(0);
       tbInformacoesServico.getColumnModel().getColumn(3).setPreferredWidth(0);
       tbInformacoesServico.getColumnModel().getColumn(4).setPreferredWidth(0);

       modelo2.addColumn("Item");
       modelo2.addColumn("Serviço");
       modelo2.addColumn("Valor - Peca");
       modelo2.addColumn("Quantidade");
       modelo2.addColumn("Valor Total Pecas");
       modelo2.addColumn("Mão de Obra");
       tbRelatorioFinal.setModel(modelo2);
       tbRelatorioFinal.getColumnModel().getColumn(0).setPreferredWidth(0);
       tbRelatorioFinal.getColumnModel().getColumn(1).setPreferredWidth(0);
       tbRelatorioFinal.getColumnModel().getColumn(2).setPreferredWidth(0);
       tbRelatorioFinal.getColumnModel().getColumn(3).setPreferredWidth(0);
       tbRelatorioFinal.getColumnModel().getColumn(4).setPreferredWidth(0);
       tbRelatorioFinal.getColumnModel().getColumn(5).setPreferredWidth(0);
    }
    
    public boolean validarCampos(JTextField textField ,String nomeTextField){
        String campo = textField.getText().trim();
        
        if( campo.isEmpty()){
            JOptionPane.showMessageDialog(this, ""+nomeTextField +" está vazio! ");
            textField.requestFocus();
            return false;
        }return true;
    }
    
    public boolean validarCampos(JTextArea textArea ,String nomeTextArea){
        String campo = textArea.getText().trim();
        
        if( campo.isEmpty()){
            JOptionPane.showMessageDialog(this, ""+nomeTextArea +" está vazio! ");
            textArea.requestFocus();
            return false;
        }
        return true;
    }
    
    public boolean validarNumeros(JTextField textField, String nomeTextString){
        String campo = textField.getText().trim();
        
        if (campo.isEmpty()) {
            return false;
        }
        
        for (int i = 0; i < campo.length(); i++) {
            char c = campo.charAt(i);
            if (c < '0' || c > '9') {
                
                JOptionPane.showMessageDialog(this, ""+nomeTextString +" - somente Números! ");
                textField.requestFocus();
                return false;
            }
        }
        return true;    
    } 
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btEntrar = new javax.swing.JButton();
        tfUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfSenha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLogradouro = new javax.swing.JLabel();
        jNome = new javax.swing.JLabel();
        jCliente = new javax.swing.JLabel();
        jVeiculo = new javax.swing.JLabel();
        tfNomeCliente = new javax.swing.JTextField();
        tfNomeVeiculo = new javax.swing.JTextField();
        jNomeCliente = new javax.swing.JLabel();
        jPlaca = new javax.swing.JLabel();
        jNumero = new javax.swing.JLabel();
        tfPlacaVeiculo = new javax.swing.JTextField();
        tfLogradouroCliente = new javax.swing.JTextField();
        tfNumeroCliente = new javax.swing.JTextField();
        jAno = new javax.swing.JLabel();
        tfAnoVeiculo = new javax.swing.JTextField();
        jTelefone = new javax.swing.JLabel();
        tfTelefoneCliente = new javax.swing.JTextField();
        tfQuilometragemVeiculo = new javax.swing.JTextField();
        jQuilometragem = new javax.swing.JLabel();
        buttonSalvarDados = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        spServicoeCustos = new javax.swing.JScrollPane();
        taPreDiagnostico = new javax.swing.JTextArea();
        spServicoeCustos1 = new javax.swing.JScrollPane();
        taPreServicosCustos1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tfPeca = new javax.swing.JTextField();
        tfValorPeca = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfValorMaodeObra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tfSubTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btSalvarOrcamento = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tfQuantidadePecas = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfServico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInformacoesServico = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbRelatorioFinal = new javax.swing.JTable();
        spRelatorioFinal = new javax.swing.JScrollPane();
        tpRelatorioFinal = new javax.swing.JTextPane();
        jLabel21 = new javax.swing.JLabel();
        tfValorFinal = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        spRelatorioFinal1 = new javax.swing.JScrollPane();
        tpInformacoesCliente = new javax.swing.JTextPane();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cliente/Veiculo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Orcamento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Relatório de Servico");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(559, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 753));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(651, 740));

        btEntrar.setBackground(new java.awt.Color(237, 237, 237));
        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuário: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("A.S AUTO-CAR");
        jLabel3.setToolTipText("");
        jLabel3.setAutoscrolls(true);

        jLabel2.setText("Senha:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btEntrar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(tfUsuario, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(223, 223, 223))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btEntrar)
                .addContainerGap(473, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jLogradouro.setText("Logradouro");

        jNome.setText("Nome");

        jCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCliente.setText("Cliente ");

        jVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jVeiculo.setText("Veículo");

        jNomeCliente.setText("Nome ");

        jPlaca.setText("Placa");

        jNumero.setText("Número");

        jAno.setText("Ano");

        jTelefone.setText("Telefone");

        jQuilometragem.setText("Quilometragem");

        buttonSalvarDados.setText("Salvar Dados");
        buttonSalvarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarDadosActionPerformed(evt);
            }
        });

        jLabel19.setText("Pré Diagnóstico");

        jLabel20.setText("Registro de Pré-Servicos, Custos e afins: ");

        taPreDiagnostico.setColumns(20);
        taPreDiagnostico.setRows(5);
        spServicoeCustos.setViewportView(taPreDiagnostico);

        taPreServicosCustos1.setColumns(20);
        taPreServicosCustos1.setRows(5);
        spServicoeCustos1.setViewportView(taPreServicosCustos1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spServicoeCustos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                                    .addComponent(jLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jNomeCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfNomeCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfLogradouroCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfTelefoneCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(104, 104, 104))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(81, 81, 81))
                            .addComponent(jVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jQuilometragem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfPlacaVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAnoVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(buttonSalvarDados, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfQuilometragemVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(spServicoeCustos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfNomeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCliente)
                    .addComponent(jVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome)
                    .addComponent(jNomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogradouro)
                    .addComponent(jPlaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLogradouroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumero)
                    .addComponent(jAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTelefone)
                    .addComponent(jQuilometragem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQuilometragemVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(spServicoeCustos1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSalvarDados))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spServicoeCustos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jLabel14.setText("Peça");

        tfPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPecaActionPerformed(evt);
            }
        });

        jLabel15.setText("Valor - Peca");

        jLabel16.setText("Valor - Mão de Obra");

        tfSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSubTotalActionPerformed(evt);
            }
        });

        jLabel17.setText("Sub Total");

        btSalvarOrcamento.setText("Salvar");
        btSalvarOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarOrcamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btSalvarOrcamento)))
                .addGap(15, 15, 15))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvarOrcamento)
                .addGap(17, 17, 17)
                .addComponent(jLabel17)
                .addGap(5, 5, 5)
                .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jLabel18.setText("Quantidade");

        jLabel24.setText("Serviço");

        tbInformacoesServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item ", "Serviço", "Peça", "Quantidade", "Mão de obra"
            }
        ));
        jScrollPane1.setViewportView(tbInformacoesServico);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfServico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(tfPeca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfValorPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfQuantidadePecas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfValorMaodeObra))
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfValorMaodeObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfValorPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQuantidadePecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        tbRelatorioFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Pecas", "Servico", "Valor Unitario Peca", "Quantidade", "Valor total Pecas", "Mão de obra"
            }
        ));
        jScrollPane4.setViewportView(tbRelatorioFinal);

        spRelatorioFinal.setViewportView(tpRelatorioFinal);

        jLabel21.setText("Relatório Final");

        jLabel22.setText("Valor Total");

        spRelatorioFinal1.setViewportView(tpInformacoesCliente);

        jLabel23.setText("Cliente");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spRelatorioFinal1)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfValorFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(spRelatorioFinal)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spRelatorioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spRelatorioFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, -37, -1, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonSalvarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarDadosActionPerformed
        
        if(!validarCampos( tfNomeCliente, "Nome do Cliente" )){
            return;}
        if(!validarCampos( tfLogradouroCliente, "Logradouro do Cliente" )){
            return;}
        if(!validarNumeros( tfNumeroCliente, "Número do Cliente" )){
            return;}        
        if(!validarNumeros(tfTelefoneCliente, "Telefone do Cliente")){
            return;}
        if(!validarCampos( tfNomeVeiculo, "Nome do Veiculo" )){
            return;}
        if(!validarCampos( tfPlacaVeiculo, "Placa do Veiculo" )){
            return;}
        if(!validarNumeros( tfAnoVeiculo, "Ano do Veiculo" )){
            return;}
        if(!validarNumeros( tfQuilometragemVeiculo, "Quilometragem do Veiculo" )){
            return;}        
        if(!validarCampos(taPreDiagnostico, "Pré Diagnóstico")){
            return;}
        if(!validarCampos(taPreDiagnostico, "Pré Orçamento" )){
            return;}
        
        JOptionPane.showMessageDialog(jPanel2, "Dados salvos com Sucesso!");
        jTabbedPane1.setSelectedIndex(2);
        cliente.setNomeCliente(tfNomeCliente.getText());
        cliente.setLogradouroCliente(tfLogradouroCliente.getText());
        cliente.setNumeroCliente(tfNumeroCliente.getText());        
        cliente.setTelefoneCliente(tfTelefoneCliente.getText());
        veiculo.setNomeVeiculo(tfNomeVeiculo.getText());
        veiculo.setPlacaVeiculo(tfPlacaVeiculo.getText());
        veiculo.setAnoVeiculo(tfAnoVeiculo.getText());
        veiculo.setQuilometragemVeiculo(tfQuilometragemVeiculo.getText());
        servicos.setPreDiagnostico(taPreDiagnostico.getText());
        servicos.setPreServicosCustos(taPreDiagnostico.getText());
        
        tfNomeCliente.setText("");
        tfLogradouroCliente.setText("");
        tfNumeroCliente.setText("");
        tfTelefoneCliente.setText("");
        tfNomeVeiculo.setText("");
        tfPlacaVeiculo.setText("");
        tfAnoVeiculo.setText("");
        tfQuilometragemVeiculo.setText("");
        taPreDiagnostico.setText("");
        taPreDiagnostico.setText("");
        
    }//GEN-LAST:event_buttonSalvarDadosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTabbedPane1.setSelectedIndex(3);
        
        tpRelatorioFinal.setText( ""
                + "Veículo: " + veiculo.getNomeVeiculo() + "\n"
                + "Placa: " + veiculo.getPlacaVeiculo()+ "\n"
                + "Ano: " + veiculo.getAnoVeiculo()+ "\n"
                + "Quilometragem: " + veiculo.getQuilometragemVeiculo()+ "\n"
                + "________________________________________________________\n"
                + "Chegou em nossa Oficina com o seguinte Diagnóstico: \n"
                        + servicos.getPreDiagnostico() + "\n"
                        + "________________________________________________________\n"
                        + "Recebeu os seguintes Servicos: \n"
                                + servicos.getPreServicosCustos()+"");
        
        tpInformacoesCliente.setText(""
                + "Cliente : " + cliente.getNomeCliente() + "\n"
                + "Rua : " + cliente.getLogradouroCliente() + "\n"
                + "Número : " + cliente.getNumeroCliente() + "\n"
                + "Telefone : " + cliente.getTelefoneCliente() + "\n");
        
        tfValorFinal.setText(servicos.getSubTotal());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
         
        String nomeUsuario = tfUsuario.getText();
        String senhaUsuario = tfSenha.getText();
        
        if( nomeUsuario.isEmpty()){
            JOptionPane.showMessageDialog(this, "Usuário inválido!");  
        }if( senhaUsuario.isEmpty()){
            JOptionPane.showMessageDialog(this, "Senha inválida!");  
        }else{
            JOptionPane.showMessageDialog(jPanel2, "Bem Vindo(a)!");
            jTabbedPane1.setSelectedIndex(1);
        }
    }//GEN-LAST:event_btEntrarActionPerformed

    private void btSalvarOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarOrcamentoActionPerformed
      
        if(!validarCampos( tfPeca, "Peça" )){
            return;}
        if(!validarNumeros(tfValorPeca, "Valor das Peças" )){
            return;}
        if(!validarNumeros( tfQuantidadePecas, "Quantidade de Peças" )){
            return;}        
        if(!validarNumeros(tfValorMaodeObra, "Mão de Obra")){
            return;}
        if(!validarCampos( tfServico, "Valor de Serviço" )){
            return;}
        
        servicos.setItem(tfPeca.getText());
        servicos.setServico(tfServico.getText());
        servicos.setValorPecaServico(tfValorPeca.getText());
        servicos.setQuantidadePecas(tfQuantidadePecas.getText());
        servicos.setValorMaodeObra(tfValorMaodeObra.getText());
        
       
        //Para informar ao cliente o valor de todas as pecas * quantidade, utilizei valorTotalPecas
        //Para informar ao cliente o valor das pecas * quantidade utilizei valorTotalPeca
        //Por isso duas variaveis (quase) iguais.
        servicos.setValorTotalPecas((Double.valueOf(servicos.getValorPecaServico()) * Double.valueOf(servicos.getQuantidadePecas())) + servicos.getValorTotalPecas());
        servicos.setValorTotalPeca((Double.valueOf(servicos.getValorPecaServico()) * Double.valueOf(servicos.getQuantidadePecas())));
        servicos.setValorTotalMaodeObra(Double.valueOf(servicos.getValorMaodeObra()) + servicos.getValorTotalMaodeObra());
        
        if( linhaSelecionada >= 0 ){
            modelo.removeRow(linhaSelecionada);
            modelo2.removeRow(linhaSelecionada);
            modelo.insertRow(linhaSelecionada, new Object[] {servicos.getItem(),servicos.getServico() ,servicos.getValorPecaServico(), servicos.getQuantidadePecas(), servicos.getValorMaodeObra()});
            modelo2.insertRow(linhaSelecionada, new Object[] {servicos.getItem(),servicos.getServico() ,servicos.getValorPecaServico(), servicos.getQuantidadePecas(), servicos.getValorTotalPeca(), servicos.getValorMaodeObra()});
        }else{
            modelo.addRow(new Object[] {servicos.getItem(),servicos.getServico() ,servicos.getValorPecaServico(), servicos.getQuantidadePecas(), servicos.getValorMaodeObra()});
            modelo2.addRow(new Object[] {servicos.getItem(),servicos.getServico() ,servicos.getValorPecaServico(), servicos.getQuantidadePecas(), servicos.getValorTotalPeca(), servicos.getValorMaodeObra()});
        }

        JOptionPane.showMessageDialog(jPanel2, "Orcamento salvo com Sucesso!");

        tfPeca.setText("");
        tfValorPeca.setText("");
        tfQuantidadePecas.setText("");
        tfValorMaodeObra.setText("");
        tfServico.setText("");
        tfPeca.requestFocus();
        tfValorPeca.requestFocus();
        tfQuantidadePecas.requestFocus();
        tfValorMaodeObra.requestFocus();
        linhaSelecionada = -1;
        
        tfSubTotal.setText("R$ " + String.valueOf(servicos.getValorTotalPecas() + servicos.getValorTotalMaodeObra()));
        servicos.setSubTotal(tfSubTotal.getText());
    }//GEN-LAST:event_btSalvarOrcamentoActionPerformed

    private void tfPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPecaActionPerformed

    private void tfSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSubTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton btSalvarOrcamento;
    private javax.swing.JButton buttonSalvarDados;
    private javax.swing.JLabel jAno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLogradouro;
    private javax.swing.JLabel jNome;
    private javax.swing.JLabel jNomeCliente;
    private javax.swing.JLabel jNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jPlaca;
    private javax.swing.JLabel jQuilometragem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jTelefone;
    private javax.swing.JLabel jVeiculo;
    private javax.swing.JScrollPane spRelatorioFinal;
    private javax.swing.JScrollPane spRelatorioFinal1;
    private javax.swing.JScrollPane spServicoeCustos;
    private javax.swing.JScrollPane spServicoeCustos1;
    private javax.swing.JTextArea taPreDiagnostico;
    private javax.swing.JTextArea taPreServicosCustos1;
    private javax.swing.JTable tbInformacoesServico;
    private javax.swing.JTable tbRelatorioFinal;
    private javax.swing.JTextField tfAnoVeiculo;
    private javax.swing.JTextField tfLogradouroCliente;
    private javax.swing.JTextField tfNomeCliente;
    private javax.swing.JTextField tfNomeVeiculo;
    private javax.swing.JTextField tfNumeroCliente;
    private javax.swing.JTextField tfPeca;
    private javax.swing.JTextField tfPlacaVeiculo;
    private javax.swing.JTextField tfQuantidadePecas;
    private javax.swing.JTextField tfQuilometragemVeiculo;
    private javax.swing.JTextField tfSenha;
    private javax.swing.JTextField tfServico;
    private javax.swing.JTextField tfSubTotal;
    private javax.swing.JTextField tfTelefoneCliente;
    private javax.swing.JTextField tfUsuario;
    private javax.swing.JTextField tfValorFinal;
    private javax.swing.JTextField tfValorMaodeObra;
    private javax.swing.JTextField tfValorPeca;
    private javax.swing.JTextPane tpInformacoesCliente;
    private javax.swing.JTextPane tpRelatorioFinal;
    // End of variables declaration//GEN-END:variables
}

